on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Build and test 
      run: |
        cd lumino
        yarn
        yarn run build:tsc
        yarn run test:firefox:headless

