on: [push, pull_request]
name: Python
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-
      - name: Install flit
        run: |
          python -m pip install --upgrade pip
          pip install flit
      - name: Install package
        run: flit install
        working-directory: ./packages/jupyter-graphql
      - name: Run tests
        run: pytest jupyter_graphql/
        working-directory: ./packages/jupyter-graphql
  format:
    name: Run black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install black
        run: pip install black
      - name: Test black format
        run: black --check
        working-directory: ./packages/jupyter-graphql
